export const confWeapons = [
        {
          id : 1,
          nom : "Pierre",
          bat : [3,5,10,12,15,18,21],
          lvl : 1,
          img : require("../images/pierre.png"),
        },
        {
          id : 2,
          nom : "Papier",
          bat : [1,4,18,23],
          lvl : 1,
          img : require("../images/papier.png"),
        },
        {
          id : 3,
          nom : "Ciseaux",
          bat : [2,6,9,14,17,18,20,22,27],
          lvl : 1,
          img : require("../images/ciseaux.png"),
        },
        {
          id : 4,
          nom : "Puits",
          bat : [1,3,8,10,25],
          lvl : 2,
          img : require("../images/puit.png"),
        },
        {
          id : 5,
          nom : "Bazooka",
          bat : [2,3,4,14,18,20,25],
          lvl : 3,
          img : require("../images/bazooka.png"),
        },
        {
          id : 6,
          nom : "Licorne",
          bat : [2,5,8,13,16],
          lvl : 4,
          img : require("../images/licorne.png"),
        },
        {
          id : 7,
          nom : "The ULTIMATE",
          bat : [1,2,3,4,5,7,9,12,15,16,21,23,24,25,26],
          lvl : 20,
          img : require("../images/ultimate.png"),
        },
        {
          id : 8,
          nom : "Spartiate",
          bat : [1,3,5,13,14,18,20],
          lvl : 6,
          img : require("../images/spartiate.png"),
        },
        {
          id : 9,
          nom : "Corde",
          bat : [1,4,6,17,22,25,27],
          lvl : 10,
          img : require("../images/corde.png"),
        },
        {
          id : 10,
          nom : "Bière",
          bat : [7,8,11,13,17,18],
          lvl : 6,
          img : require("../images/biere.png"),
        },
        {
          id : 11,
          nom : "Arc-en-ciel",
          bat : [5,6,7,22,25,27],
          lvl : 7,
          img : require("../images/rainbow.png"),
        },
        {
          id : 12,
          nom : "Poulet",
          lvl : 8,
          bat : [8,9,18],
          img : require("../images/poulet.png"),
        },
        {
          id : 13,
          nom : "Café",
          lvl : 9,
          bat : [2,7,25],
          img : require("../images/cafe.png"),
        },
        {
          id : 14,
          nom : "Oreiller",
          lvl : 11,
          bat : [7,18,19],
          img : require("../images/oreiller.png"),
        },
        {
          id : 15,
          nom : "Poulet Musclé",
          lvl : 8,
          bat : [8,9,18],
          img : require("../images/poulet_muscle.png"),
          price : 100,
        },
        {
          id : 16,
          nom : "Sabre Laser",
          lvl : 9,
          bat : [1,4,8,9,26],
          img : require("../images/lasersaber.png"),
        },
        {
          id : 17,
          nom : "Slip",
          lvl : 13,
          bat : [8,11,12,15,19,21,25],
          img : require("../images/slip.png"),
        },
        {
          id : 18,
          nom : "Elève",
          lvl : 13,
          bat : [16,17,23],
          img : require("../images/student.png"),
        },
        {
          id : 19,
          nom : "Pin-Up",
          lvl : 14,
          bat : [6,7,8,18,22,27],
          img : require("../images/pinup.png"),
        },
        {
          id : 20,
          nom : "Pink Metal Pillow",
          lvl : 11,
          bat : [7,18,19],
          img : require("../images/oreiller_metal.png"),
          price : 100,
        },
        {
          id : 21,
          nom : "Poulet Rôti",
          lvl : 8,
          bat : [8,9,18],
          img : require("../images/poulet_roti.png"),
          price : 150,
        },
        {
          id : 22,
          nom : "Licorne Arc-En-Ciel",
          bat : [2,5,8,13,16],
          lvl : 4,
          img : require("../images/rainbow_unicorn.png"),
          price : 300,
        },
        {
          id : 23,
          nom : "Nugget Cosmique",
          lvl : 15,
          bat : [12,15,17,21],
          img : require("../images/cosmic_nugget.png"),
        },
        {
          id : 24,
          nom : "Rainbow UniCat",
          bat : [5,6,8,10,22,23,27],
          lvl : 1,
          img : require("../images/unicat.png"),
          price : 3000,
        },
        {
          id : 25,
          nom : "Hamster Bondage",
          bat : [2,6,18,22,26,27],
          lvl : 16,
          img : require("../images/hamster_bondage.png"),
        },
        {
          id : 26,
          nom : "Phoque",
          bat : [17,18,19,23],
          lvl : 17,
          img : require("../images/phoque.png"),
        },
        {
          id : 27,
          nom : "Robot Unicorn",
          bat : [2,5,8,13,16],
          lvl : 4,
          img : require("../images/robot_licorne.png"),
          price : 500,
        },
      ];
