export const confWeapons = [
        {
          id : 1,
          nom : "Pierre",
          type : 1,
          lvl : 1,
          img : require("../images/pierre.png"),
        },
        {
          id : 2,
          nom : "Papier",
          type : 2,
          lvl : 1,
          img : require("../images/papier.png"),
        },
        {
          id : 3,
          nom : "Ciseaux",
          type : 3,
          lvl : 1,
          img : require("../images/ciseaux.png"),
        },
        {
          id : 4,
          nom : "Puits",
          type : 4,
          lvl : 2,
          img : require("../images/puit.png"),
        },
        {
          id : 5,
          nom : "Bazooka",
          type : 5,
          lvl : 3,
          img : require("../images/bazooka.png"),
        },
        {
          id : 6,
          nom : "Licorne",
          type : 6,
          lvl : 4,
          img : require("../images/licorne.png"),
        },
        {
          id : 8,
          nom : "Spartiate",
          type : 8,
          lvl : 6,
          img : require("../images/spartiate.png"),
        },
        {
          id : 9,
          nom : "Corde",
          type : 9,
          lvl : 10,
          img : require("../images/corde.png"),
        },
        {
          id : 10,
          nom : "Bière",
          type : 10,
          lvl : 6,
          img : require("../images/biere.png"),
        },
        {
          id : 11,
          nom : "Arc-en-ciel",
          type : 11,
          lvl : 7,
          img : require("../images/rainbow.png"),
        },
        {
          id : 12,
          nom : "Poulet",
          lvl : 8,
          type : 12,
          img : require("../images/poulet.png"),
        },
        {
          id : 13,
          nom : "Café",
          lvl : 9,
          type : 13,
          img : require("../images/cafe.png"),
        },
        {
          id : 14,
          nom : "Oreiller",
          lvl : 11,
          type : 14,
          img : require("../images/oreiller.png"),
        },
        {
          id : 15,
          nom : "Poulet Musclé",
          lvl : 8,
          type : 12,
          img : require("../images/poulet_muscle.png"),
          price : 100,
        },
        {
          id : 16,
          nom : "Sabre Laser",
          lvl : 9,
          type : 16,
          img : require("../images/lasersaber.png"),
        },
        {
          id : 17,
          nom : "Slip",
          lvl : 13,
          type : 17,
          img : require("../images/slip.png"),
        },
        {
          id : 18,
          nom : "Victime",
          lvl : 13,
          type : 18,
          img : require("../images/student.png"),
        },
        {
          id : 19,
          nom : "Pin-Up",
          lvl : 14,
          type : 19,
          img : require("../images/pinup.png"),
        },
        {
          id : 20,
          nom : "Pink Metal Pillow",
          lvl : 11,
          type : 14,
          img : require("../images/oreiller_metal.png"),
          price : 100,
        },
        {
          id : 21,
          nom : "Poulet Rôti",
          lvl : 8,
          type : 12,
          img : require("../images/poulet_roti.png"),
          price : 150,
        },
        {
          id : 22,
          nom : "Licorne Arc-En-Ciel",
          type : 6,
          lvl : 4,
          img : require("../images/rainbow_unicorn.png"),
          price : 300,
        },
        {
          id : 23,
          nom : "Nugget Cosmique",
          lvl : 15,
          type : 23,
          img : require("../images/cosmic_nugget.png"),
        },
        {
          id : 24,
          nom : "Rainbow UniCat",
          type : 24,
          lvl : 10,
          img : require("../images/unicat.png"),
          price : 3000,
        },
        {
          id : 25,
          nom : "Hamster Bondage",
          type : 25,
          lvl : 16,
          img : require("../images/hamster_bondage.png"),
        },
        {
          id : 26,
          nom : "Phoque",
          type : 26,
          lvl : 17,
          img : require("../images/phoque.png"),
        },
        {
          id : 27,
          nom : "Robot Unicorn",
          type : 6,
          lvl : 4,
          img : require("../images/robot_licorne.png"),
          price : 500,
        },
        {
          id : 28,
          nom : "The ULTIMATE ULTIMATE",
          type : 7,
          lvl : 20,
          img : require("../images/moi-lv-up.png"),
          price : 4000000,
        },
        {
          id : 29,
          nom : "Chou-riken",
          type : 29,
          lvl : 25,
          img : require("../images/chouriken.png"),
        },
        {
          id : 27,
          nom : "Angry Unicorn",
          type : 6,
          lvl : 6,
          img : require("../images/unicorn.png"),
          price : 750,
        },
        {
          id : 28,
          nom : "Ornithorynque",
          type : 15,
          lvl : 27,
          img : require("../images/platypus.png"),
        },
        {
          id : 7,
          nom : "The ULTIMATE",
          type : 7,
          lvl : 50,
          img : require("../images/ultimate.png"),
        },
      ];
