export const confWeapons = [
        {
          id : 1,
          nom : "Pierre",
          bat : [3,5,10,12,15],
          lvl : 1,
          img : require("../images/pierre.png"),
        },
        {
          id : 2,
          nom : "Papier",
          bat : [1,4],
          lvl : 1,
          img : require("../images/papier.png"),
        },
        {
          id : 3,
          nom : "Ciseaux",
          bat : [2,6,9,14],
          lvl : 1,
          img : require("../images/ciseaux.png"),
        },
        {
          id : 4,
          nom : "Puit",
          bat : [1,3,8,10],
          lvl : 2,
          img : require("../images/puit.png"),
        },
        {
          id : 5,
          nom : "Bazooka",
          bat : [2,3,4,14],
          lvl : 3,
          img : require("../images/bazooka.png"),
        },
        {
          id : 6,
          nom : "Licorne",
          bat : [2,5,8,13,16],
          lvl : 4,
          img : require("../images/licorne.png"),
        },
        {
          id : 7,
          nom : "The ULTIMATE",
          bat : [1,2,3,4,5,7,9,12,15,16],
          lvl : 20,
          img : require("../images/ultimate.png"),
        },
        {
          id : 8,
          nom : "Spartiate",
          bat : [1,2,3,5,13,14],
          lvl : 6,
          img : require("../images/spartiate.png"),
        },
        {
          id : 9,
          nom : "Corde",
          bat : [1,4,6],
          lvl : 3,
          img : require("../images/corde.png"),
        },
        {
          id : 10,
          nom : "Bière",
          bat : [7,8,11,13],
          lvl : 6,
          img : require("../images/biere.png"),
        },
        {
          id : 11,
          nom : "Arc-en-ciel",
          bat : [5,6,7],
          lvl : 7,
          img : require("../images/rainbow.png"),
        },
        {
          id : 12,
          nom : "Poulet",
          lvl : 8,
          bat : [8,9],
          img : require("../images/poulet.png"),
        },
        {
          id : 13,
          nom : "Café",
          lvl : 9,
          bat : [2,7],
          img : require("../images/cafe.png"),
        },
        {
          id : 14,
          nom : "Oreiller",
          lvl : 10,
          bat : [7],
          img : require("../images/oreiller.png"),
        },
        {
          id : 15,
          nom : "Poulet Musclé",
          lvl : 8,
          bat : [8,9],
          img : require("../images/poulet_muscle.png"),
          price : 100,
        },
        {
          id : 16,
          nom : "Sabre Laser",
          lvl : 9,
          bat : [1,4,8,9],
          img : require("../images/lasersaber.png"),
        },
      ];
